#!/bin/sh
# find all files with the extension pch and touch them
print_usage ()
{
	echo "Usage: `basename $0` [-d n] path";
	exit 1;
}
dflag=
while getopts ":d:" opt; do
    case $opt in
        d)
            dflag=1;
            dval="$OPTARG";
            ;;
        :)
            print_usage;
            ;;
    esac
done
shift $(($OPTIND - 1))

if [ -z "$1" ]; then
    print_usage;
fi

path="${1}";

if [ ! -d "${path}" ]; then
    echo "Not a path: $path";
    exit 2;
fi

/usr/bin/find "${path}" -maxdepth 1 -iname "*.pch" -exec touch {} +;
